export interface MoveOrderLinePayload {
    // --- MANDATORY FIELDS (Sesuai Highlight Biru di Excel) ---
    line_number: number;
    organization_id: number;
    inventory_item_id: number;
    from_subinventory_code: string;
    from_locator_id: number; // Ingat: ini butuh query BE dari XTD_INV_WAREHOUSES_V
    to_subinventory_code: string; // Butuh query BE dari XTD_ONT_SALESREPS_V
    to_locator_id: number; // Butuh query BE dari XTD_ONT_SALESREPS_V
    uom_code: string;
    quantity: number;
    date_required: string;
    transaction_type_id: number;
    transaction_source_type_id: number;
    line_status: number;
    status_date: string;
    operation: string;
    db_flag: string;
    source_system: string;
    source_header_id: string;
    source_line_id: string;
    iface_status: string;
    creation_date: string;
    created_by: number | string;
    last_update_date: string;
    last_updated_by: number | string;

    // --- OPTIONAL FIELDS (Tidak di-highlight biru) ---
    move_order_integration_id?: string;
    line_iface_id?: number;
    header_iface_id?: number;
    revision?: string;
    from_subinventory_id?: number;
    to_organization_id?: number;
    to_subinventory_id?: number;
    to_account_id?: number;
    lot_number?: string;
    serial_number_start?: string;
    serial_number_end?: string;
    quantity_delivered?: number;
    quantity_detailed?: number;
    reason_id?: number;
    reference_id?: number;
    reference?: string;
    reference_type_code?: number;
    project_id?: number;
    task_id?: number;
    transaction_header_id?: number;
    txn_source_id?: number;
    txn_source_line_id?: number;
    txn_source_line_detail_id?: number;
    primary_quantity?: number;
    put_away_strategy_id?: number;
    pick_strategy_id?: number;
    unit_number?: string;
    ship_to_location_id?: number;
    from_cost_group_id?: number;
    to_cost_group_id?: number;
    lpn_id?: number;
    to_lpn_id?: number;
    pick_methodology_id?: number;
    container_item_id?: number;
    carton_grouping_id?: number;
    inspection_status?: number;
    wms_process_flag?: number;
    pick_slip_number?: number;
    pick_slip_date?: string;
    ship_set_id?: number;
    ship_model_id?: number;
    model_quantity?: number;
    required_quantity?: number;
    secondary_uom?: string;
    secondary_quantity?: number;
    secondary_quantity_detailed?: number;
    secondary_quantity_delivered?: number;
    secondary_required_quantity?: number;
    grade_code?: string;
    attribute_category?: string;
    attribute1?: string;
    attribute2?: string;
    attribute3?: string;
    attribute4?: string;
    attribute5?: string;
    attribute6?: string;
    attribute7?: string;
    attribute8?: string;
    attribute9?: string;
    attribute10?: string;
    attribute11?: string;
    attribute12?: string;
    attribute13?: string;
    attribute14?: string;
    attribute15?: string;
    program_application_id?: number;
    program_id?: number;
    program_update_date?: string;
    line_id?: number;
    header_id?: number;
    transaction_temp_id?: number;
    request_id?: number;
    source_batch_id?: string;
    iface_message?: string;
    last_update_login?: number;
}