const dummyCallplan = [
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000036.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2266",
        "SALES_NAME": "SYARIF NUR HAKIM",
        "SALES_NIK": "250616.00033BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "ODI ARIANSYAH",
        "SALES_NIK": "250217.00024BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "NUR ROBI",
        "SALES_NIK": "231116.00284BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "YULIRANTO ZAI",
        "SALES_NIK": "250521.00031BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "M. FAJAR RAMADHAN",
        "SALES_NIK": "260223.00051BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "TANGERANG TSF-06",
        "SALES_NIK": "TGR.TSF06",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000037.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2271",
        "SALES_NAME": "TANGERANG TSF-09",
        "SALES_NIK": "TGR.TSF09",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "MOHAMAD ABDUROKHMAN",
        "SALES_NIK": "151109.00233BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "PARMIN",
        "SALES_NIK": "960401.00736B0",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "RANDY AJI RUSDIANTO",
        "SALES_NIK": "250811.00036BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "DIDIN NURHAEDIN",
        "SALES_NIK": "241001.00015BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "MUHAMAD AGRIANSYAH",
        "SALES_NIK": "250217.00023BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "GANJAR BAHTIAR",
        "SALES_NIK": "260511.00062BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000038.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2270",
        "SALES_NAME": "NUR ROBI",
        "SALES_NIK": "241116.00002BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000040.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "1811",
        "SALES_NAME": "MUHAMAD FAHRI ALFARISHI",
        "SALES_NIK": "260420.00060BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "ARIF HAERUDIN",
        "SALES_NIK": "051109.00081BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000034.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2262",
        "SALES_NAME": "AHMAD FERI MUHTADIN",
        "SALES_NIK": "260302.00053BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000039.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "1829",
        "SALES_NAME": "FENDI RIDHO MAYA SUKMA",
        "SALES_NIK": "260407.00059BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000035.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2272",
        "SALES_NAME": "TANGERANG TSF-08",
        "SALES_NIK": "TGR.TSF08",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "ALBERTUS RETMANDA",
        "SALES_NIK": "220124.00269BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "IMAM RESTU PRIBADI",
        "SALES_NIK": "251001.00037BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "2026-06-02",
        "CALL_PLAN_NUMBER": "TGR/2026/6/000033.1",
        "CALL_PLAN_START_DATE": "2026-06-02",
        "ROUTE_NUMBER": "2286",
        "SALES_NAME": "TANGERANG TSF-22",
        "SALES_NIK": "TGR.TSF22",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": true
    },
    {
        "AHOM_NAME": "SUPRIYADI",
        "AHOM_NIK": "100104.01871B0",
        "CABANG": "TGR",
        "CALL_PLAN_END_DATE": "-",
        "CALL_PLAN_NUMBER": "-",
        "CALL_PLAN_START_DATE": "-",
        "ROUTE_NUMBER": "-",
        "SALES_NAME": "DIDIN NURHAEDIN",
        "SALES_NIK": "241001.00016BC",
        "SALES_SUPERVISOR_NAME": "RIDHO AZHARIANTO",
        "SALES_SUPERVISOR_NIK": "240801.00011BC",
        "is_active_plan": false
    }
]


export default dummyCallplan